name: Deploy AKS cluster
on:
    workflow_dispatch:
        inputs:
            aks_exit_code:
                description: "AKS Exit code"
                required: true
                type: number
            helm_exit_code:
                description: "Helm Exit code"
                required: true
                type: number


permissions: read-all

jobs:
  
    aks:
        name: Deploy Cluster
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Run something
            run: |
                echo "Hello World"
                echo ${{ inputs.aks_exit_code }}
                echo ${{ inputs.helm_exit_code }}
                exit ${{ inputs.aks_exit_code }}

    helm:
        name: Deploy helm chart
        needs: [ aks ]
        if: ${{ always() && (needs.aks.result != 'failure') }}
        uses: ./.github/workflows/helm.yml
        with:
            helm_exit_code: "${{ inputs.helm_exit_code }}"
                        
    aks_failure:
        name: Raise incident
        needs: [ aks ]
        if: ${{ always() && (needs.aks.result == 'failure') }}
        uses: ./.github/workflows/incident.yml
        