name: Raise incident
on:
  workflow_call:

permissions: read-all

jobs:
  
    aks:
        name: Raise incident
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Raise incident
            run: |
                echo "Incident raised"
    