---
name: Kubeconform

on:
  workflow_dispatch:

permissions: read-all

env:
  GO_VERSION: "1.24.1"
  HELM_VERSION: "v3.17.2"
  KUBECONFORM_VERSION: "v0.6.7"

jobs:

  kubeconform:
    name: Run kubeconform
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Setup kubeconform
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@${{ env.KUBECONFORM_VERSION }}

      - name: Run kubeconform
        run: make kubeconform